name: CI - Lint / Tests / Deploy

on: [push]

jobs:

  lint:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install flake8

      - name: Lint with flake8
        run: |
          python3.9 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python3.9 -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  tests:
    needs: lint
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install pytest flake8
          if [ -f requirements.txt ]; then python3.9 -m pip install -r requirements.txt; fi

      - name: Integration Tests
        run: |
          python3.9 test.py

  deploy:
    needs: tests
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy into Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_USER_EMAIL }}
